# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testFCM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testFCM
  pod 'Firebase/Core'


end

target 'testFCM-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testFCM-tvOS

  target 'testFCM-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
